version: '3'

services:
  app:
    image: sngbmyu/ustock-backend:${TAG}
    container_name: ustock_green
    ports:
      - "8082:8080"
    networks:
      - ustock-network

networks:
  ustock-network:
    driver: bridge