name: Blue/Green Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      build_time: ${{ steps.current-time.outputs.formattedTime }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Create application.yml from Secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Get Current Time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t sngbmyu/ustock-backend:${{ steps.current-time.outputs.formattedTime }} .

      - name: Push Image to Docker Hub
        run: docker push sngbmyu/ustock-backend:${{ steps.current-time.outputs.formattedTime }}

  deploy-to-ec2:
    runs-on: [ self-hosted, Linux, X64]
    needs: build-and-push
    if: ${{ needs.build-and-push.result == 'success' }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ustock-backend:${{ needs.build-and-push.outputs.build_time }}

      - name: Update docker-compose.yml with TAG
        run: |
          sed -i "s|ustock-backend:.*|ustock-backend:${{ needs.build-and-push.outputs.build_time }}|" ${{ secrets.DOCKER_COMPOSE_BLUE_PATH }}
          sed -i "s|ustock-backend:.*|ustock-backend:${{ needs.build-and-push.outputs.build_time }}|" ${{ secrets.DOCKER_COMPOSE_GREEN_PATH }}

      - name: Deploy Blue/Green Method
        run: |
          sudo chmod +x deploy.sh
          sudo ./deploy.sh